Specify some arguments by name.
'nova boot', 'nova flavor-key', 'nova flavor-show' and the other subcommands
can be specified by a flavor name also.
But 'nova flavor-delete' and 'nova list --flavor' cannot, also 'nova list
--image' cannot be specified by a image name.
I feel it is user-friendly that a user can specify arguments by name.

By this patch, a user can do it like the following.

Before appying this patch:
 $ nova flavor-delete m1.tiny
 ERROR: Flavor m1.tiny could not be found. (HTTP 404) (Request-ID: req-af2c049f-1b77-42cf-a9ed-a3914626bc83)
 $
 $ nova list --flavor m1.tiny
 ERROR: Flavor could not be found (HTTP 422) (Request-ID: req-dbfd5df2-77d7-4a71-a3e6-b1f7fd25b96c)
 $
 $ nova list --image cirros-0.3.0-x86_64-uec

 $

After appying this patch:
 $ nova flavor-delete m1.tiny
 $
 $ nova list --flavor m1.tiny
 +--------------------------------------+--------+--------+------------------+
 | ID                                   | Name   | Status | Networks         |
 +--------------------------------------+--------+--------+------------------+
 | 2f003e0e-bfdf-4f56-bdf9-276732e640a0 | test01 | ACTIVE | private=10.0.0.2 |
 +--------------------------------------+--------+--------+------------------+
 $
 $ nova list --image cirros-0.3.0-x86_64-uec
 +--------------------------------------+--------+--------+------------------+
 | ID                                   | Name   | Status | Networks         |
 +--------------------------------------+--------+--------+------------------+
 | 2f003e0e-bfdf-4f56-bdf9-276732e640a0 | test01 | ACTIVE | private=10.0.0.2 |
 +--------------------------------------+--------+--------+------------------+
 $

Fixes bug 1091814

Change-Id: Ic7f6ce76608a448dea3c151bc349391fbf3fa456
(cherry picked from commit eaf3c366c34c64f2e0a6ce0ada2b2db7ff09fc5b)